### ISSUE TITLE
Official Release 

### ISSUE THREAD

**Issue by Mte90** [1HappyPlace/clio#1]
It is possible to release an official version?
The minimum-stability flag as dev breaks many libraries that I am using and other software :-/
As support I use on php7 without problems and works also on php 5.6.

**Comment by Mte90** [comment]
Any news for it?

**Comment by Mte90** [comment]
Actually this is very boring and create many problems...
I think that I will do a fork to avoid that issue

**Comment by 1HappyPlace** [comment]
Hi Mte90, sorry I missed that this issue was created.  Yes, it is officially released now.  I use it everyday and have not hit any issues.  I was being too conservative.  Enjoy!

**Comment by Mte90** [comment]
You have to update the `composer.json` and remove the flag, in the meantime I done a fork with that fix https://github.com/Mte90/clio

**Comment by 1HappyPlace** [comment]
Yes, forgot to change to stable.  Still getting use to composer.  Releasing the new composer.json.  Thanks for pointing this out!
